name: Build Vim

on:
  push:
    branch:
      - main
  schedule:
    - cron: '0 0 1 * *'

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: clone
      run: git clone --depth 1 https://github.com/vim/vim.git

    - name: make
      run: |
        mkdir /tmp/ujivim
        cd vim
        ./configure \
          --prefix=/tmp/ujivim \
          --enable-multibyte \
          --enable-nls \
          --enable-cscope \
          --without-x \
          --disable-xim \
          --disable-gui \
          --disable-sysmouse \
          --disable-netbeans \
          --disable-xsmp
        make install
    - name: tar
      run: tar -zcvf /tmp/ujivim.linux-amd64.tar.gz -C /tmp ujivim
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        name: commit-${{ github.sha }}
        tag_name: commit-${{ github.sha }}
        files: /tmp/ujivim.linux-amd64.tar.gz
