name: Build Vim

on:
  push:
    branch:
      - main

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: clone
      run: git clone --depth 1 https://github.com/vim/vim.git

    - name: make
      run: |
        mkdir /tmp/dist
        cd vim
        ./configure \
          --prefix=/tmp/dist \
          --enable-multibyte \
          --enable-nls \
          --enable-cscope \
          --without-x \
          --disable-xim \
          --disable-gui \
          --disable-sysmouse \
          --disable-netbeans \
          --disable-xsmp
        make install
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
    - name: tar
      run: tar -zcvf /tmp/dist.tar.gz /tmp/dist
    - name: upload artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /tmp/dist.tar.gz
        asset_name: ujivim.linux-amd64.tar.gz
        asset_content_type: application/gzip
